#!/bin/bash

# Common functions and variables for AI agent setup scripts

set -e

# Colors for output
RED='\033[0;31m'
GREEN='\033[0;32m'
BLUE='\033[0;34m'
YELLOW='\033[1;33m'
NC='\033[0m' # No Color

# Get the directory where the scripts are located (parent of scripts/)
SCRIPT_BASE_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )/.." && pwd )"

# Target project directory (can be overridden by scripts)
TARGET_DIR="${TARGET_DIR:-$(pwd)}"

# Function to copy a file and add a header comment
copy_and_comment() {
    local source="$1"
    local target="$2"
    local description="$3"

    # The base URL for the source files
    local base_url="https://github.com/disler/my-ai-agent-prompts/blob/main"

    # Calculate the relative path for the URL
    local relative_source_path="${source#$SCRIPT_BASE_DIR/}"
    local source_url="$base_url/$relative_source_path"

    # The comment to be added.
    local comment
    comment=$(printf "# This file is copied from: %s\n# Please do not edit this file directly. Instead, edit the source file and re-run the setup script.\n\n" "$source_url")

    # Create parent directory if needed
    mkdir -p "$(dirname "$target")"

    # Copy the file and prepend the comment
    (echo -e "$comment" && cat "$source") > "$target"

    echo -e "${GREEN}  ✓ Copied and commented: $description${NC}"
}

# Function to clean up old copied files
cleanup_old_copies() {
    local source_dir="$1"
    local target_dir="$2"
    local extension="${3:-.md}" # Default to .md if not provided

    if [ ! -d "$target_dir" ]; then
        return
    fi

    for target_file in "$target_dir"/*"$extension"; do
        if [ -f "$target_file" ]; then
            local filename=$(basename "$target_file")
            local source_file="$source_dir/$filename"
            if [ ! -f "$source_file" ]; then
                rm "$target_file"
                echo -e "${YELLOW}  Removed old copy: $filename${NC}"
            fi
        fi
    done
}


# Function to calculate relative path between two absolute paths
# Works on macOS without GNU coreutils
calculate_relative_path() {
    local source="$1"
    local target="$2"
    
    # Get the canonical absolute paths
    source="$(cd "$(dirname "$source")" && pwd)/$(basename "$source")"
    target="$(cd "$(dirname "$target")" && pwd)/$(basename "$target")"
    
    # Remove common prefix
    local common_part="$source"
    local result=""
    
    while [ "${target#$common_part}" = "$target" ]; do
        common_part="$(dirname "$common_part")"
        if [ -z "$result" ]; then
            result=".."
        else
            result="../$result"
        fi
    done
    
    if [ "$common_part" = "/" ]; then
        result="$result$target"
    else
        result="$result${target#$common_part/}"
    fi
    
    echo "$result"
}
